scene:
  type: 'InTheWild'
  attributes:
    img_path: '../imgs/demo_1.jpg'
  annotations_path: ''
  save_dir: '../out/demo_1'
  K: []
run:
  use_enhancement: True
  only_foreground: True 
  single_object: False  # False [compositional reconstruction], True [all instances are reconstructed as one]
  reproject: False # True [pixels are reprojected before instance reconstruction], False [direct cropping of instance, ablation of reprojection]
  depth_edge_threshold: 0.0001
  amodal_completion: 'our'  # options: 'our', null [ablation of amodal completion]
  obj_rec: 'trellis'
  depth:
    metric: 'unidepth'   # options: 'gt', 'gt_ss', 'depthanything', 'metric3d', 'unidepth'
    relative: null # options: 'marigold', 'metric3d', 'moge', null
  segmentation:
    holistic: 'entityv2'
    fg_bg: 'clipseg' # options: 'gt', 'oneformer', 'clipseg', 'largest'
    merge_masks: # merge small masks with larger neighboring masks 
      dilation: 7
      threshold: 0.5
    tagger: 'ovsam' # options: 'ovsam', null
  calibration:
    intrinsics: 'perspectivefields'  # options: 'gt', 'perspectivefields'
    pose: null  # options: 'gt', null
  clip_bg: False # True [parts of the reconstructed instaces that intersect the background mesh are trimmed]
