_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 64
  BASE_LR: 0.0012
  STEPS: (34800, 46400)
  MAX_ITER: 58000
  WARMUP_ITERS: 1812
INPUT: 
  MIN_SIZE_TRAIN: (280, 308, 336, 364, 392, 420, 448, 476, 504, 532, 560, 588, 616, 644, 672, 700, 728, 756, 784, 812, 840, 868, 896, 924, 952, 980, 1008,)
  MIN_SIZE_TEST: 532
  MAX_SIZE_TRAIN: 896
  MAX_SIZE_TEST: 896
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 3000
VIS_PERIOD: 500
DATASETS:
  TRAIN: ('SUNRGBD_train', 'SUNRGBD_val', 'Hypersim_train', 'Hypersim_val', 'ARKitScenes_train', 'ARKitScenes_val', 'Objectron_train', 'Objectron_val', 'nuScenes_train', 'nuScenes_val', 'KITTI_train', 'KITTI_val', 'COCO3D_train')
  TEST: ('SUNRGBD_test', 'Hypersim_test', 'ARKitScenes_test', 'Objectron_test', 'KITTI_test', 'nuScenes_test') 
  CATEGORY_NAMES: ('pedestrian', 'car', 'cyclist', 'van', 'truck', 'tram', 'person', 'traffic cone', 'barrier', 'motorcycle', 'bicycle', 'bus', 'trailer', 'books', 'bottle', 'camera', 'cereal box', 'chair', 'cup', 'laptop', 'shoes', 'towel', 'blinds', 'window', 'lamp', 'shelves', 'mirror', 'sink', 'cabinet', 'bathtub', 'door', 'toilet', 'desk', 'box', 'bookcase', 'picture', 'table', 'counter', 'bed', 'night stand', 'dresser', 'pillow', 'sofa', 'television', 'floor mat', 'curtain', 'clothes', 'stationery', 'refrigerator', 'board', 'kitchen pan', 'bin', 'stove', 'microwave', 'plates', 'bowl', 'oven', 'vase', 'faucet', 'tissues', 'machine', 'printer', 'monitor', 'podium', 'cart', 'projector', 'electronics', 'computer', 'air conditioner', 'drawers', 'coffee maker', 'toaster', 'potted plant', 'painting', 'bag', 'tray', 'keyboard', 'blanket', 'rack', 'phone', 'mouse', 'fire extinguisher', 'toys', 'ladder', 'fan', 'glass', 'clock', 'toilet paper', 'closet', 'fume hood', 'utensils', 'soundsystem', 'shower curtain', 'remote', 'pen', 'fireplace', 'airplane', 'train', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'wine glass', 'fork', 'knife', 'spoon', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'couch', 'dining table', 'tv', 'cell phone', 'book', 'scissors', 'teddy bear', 'hair drier', 'toothbrush')
  METRIC_DATASETS: ('SUNRGBD_train', 'SUNRGBD_val', 'Hypersim_train', 'Hypersim_val', 'ARKitScenes_train', 'ARKitScenes_val', 'Objectron_train', 'Objectron_val', 'nuScenes_train', 'nuScenes_val', 'KITTI_train', 'KITTI_val', 'COCO3D_train')
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]  # changed to rgb order
  BACKBONE:
    FREEZE_AT: 0 
    NAME: 'build_dino_backbone'
  DINO:
    NAME: 'dinov2'
    MODEL_NAME: 'vitb14'
    OUTPUT: 'dense'
    LAYER: -1
    RETURN_MULTILAYER: False
  FPN:
    IN_FEATURE: 'last_feat'
    NORM: 'LN'
    SQUARE_PAD: 896
  ANCHOR_GENERATOR:
    SIZES: [[64], [256], [512]] 
  RPN:
    IN_FEATURES: ['p2', 'p3', 'p4']
  ROI_HEADS:
    NUM_CLASSES: 50
    IN_FEATURES: ['p2', 'p3', 'p4']